### ISSUE TITLE
Expand user home in the config file

### ISSUE THREAD

**Issue by pjw91** [xolox/python-vcs-repo-mgr#1]
For a config file:

```
[repo]
local = ~/workspace/project
```

It would be better to expand the user home path in the `local` option.
It provides portability between different usernames.

This could be done by wrapping the `local` variable using `os.path.expanduser()`.

It might be either
vcs_repo_mgr/**init**.py#L175
or
vcs_repo_mgr/**init**.py#L321, 
but I'm not sure.

**Comment by xolox** [comment]
Hi and thanks for the feedback, a very reasonable request. This is now implemented in version 0.15. Can you try it out and confirm whether it works for you? (it does for me :-)

**Comment by pjw91** [comment]
Yes, it works.

Thank you!
