### ISSUE TITLE
Problem merging up in git when remote branches are not checked out locally

### ISSUE THREAD

**Issue by blaise-io** [xolox/python-vcs-repo-mgr#4]
Given

 1. I have a remote git repository 
 2. I have a master branch
 3. I have a release branch r1810 
 4. I have a release branch r1812
 5. I have a feature branch my-awesome-feature
 6. And I have the following script:

```python
import os
import random
import string

from vcs_repo_mgr.backends.git import GitRepo

repository = GitRepo(
    local=os.path.dirname(os.path.realpath(__file__)) + '/local',
    remote='git@example.org/my-remote-repo.git',
    release_scheme='branches',
    release_filter=r'^r.*',
    bare=False,
)

approved_revision = repository.merge_up(
    target_branch='r1810',
    feature_branch='my-awesome-feature',
    delete=False,
)
```

When I call this script, I get the following output:

```txt
Cloning into '/path/to/local'...
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 15 (delta 2), reused 0 (delta 0)
Receiving objects: 100% (15/15), done.
Resolving deltas: 100% (2/2), done.
Traceback (most recent call last):
  File "script.py", line 18, in <module>
    delete=False,
  File "/path/to/local/.env/lib/python2.7/site-packages/vcs_repo_mgr/__init__.py", line 1704, in merge_up
    self.create_release_branch(target_branch)
  File "/path/to/local/.env/lib/python2.7/site-packages/vcs_repo_mgr/__init__.py", line 1160, in create_release_branch
    raise ValueError(msg % branch_name)
ValueError: Failed to determine suitable parent branch for release branch 'r1810'!
```

It does work when I checkout the branches that are involved before the `merge_up` call:

```python
# ...

repository.checkout('r1810')
repository.checkout('r1812')
repository.checkout('my-awesome-feature')

approved_revision = repository.merge_up(
    target_branch='r1810',
    feature_branch='my-awesome-feature',
    delete=False,
)
```

I'd expect those branches to be checked out automatically.

**Comment by xolox** [comment]
Thanks for the clear bug report Blaise.

It actually took me a few hours to properly understand and then fix the underlying issue. The vcs-repo-mgr test suite checks that when cloning a repository branches make it from the source to the target repository, however in vcs-repo-mgr by default `bare=True` and in this configuration the issue you reported doesn't manifest...

But as soon as I tested with `bare=False` it immediately became clear that the output of the command `git branch --list --verbose` was the problem, as you also mentioned in person. While adding `--all` does list the remote branches, the output parsing started getting really nasty :disappointed:.

Then I learned about `git for-each-ref` and there was much rejoicing :smile:. I did waste a lot of time looking for `%(objectname)` to get at the global revision ids, but eventually I found it, and it works. I expect this new approach to "git branch name discovery (both local and remote)" to be much more robust.

I've just released vcs-repo-mgr 4.1 which contains the fix.
